//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhareHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPIRATIONDATE
    {
        public long LOTNUMBER { get; set; }
        public System.DateTime EXPIREDATE { get; set; }
        public int PRODUCTQUANTITY { get; set; }
        public long BARCODE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
