//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhareHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERPRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERPRODUCT()
        {
            this.ORDERDETAILS = new HashSet<ORDERDETAILS>();
        }
    
        public long ORDERID { get; set; }
        public System.DateTime ORDERDATE { get; set; }
        public System.DateTime ORDERHOUR { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> RECEPTIONDATE { get; set; }
        public Nullable<System.DateTime> RECEPTIONHOUR { get; set; }
        public Nullable<long> TOTALTOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAILS> ORDERDETAILS { get; set; }
    }
}
