//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhareHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAILS
    {
        public long ODORDERID { get; set; }
        public short ODIDBARCODE { get; set; }
        public int QUANTITY { get; set; }
        public long TOTAL { get; set; }
    
        public virtual ORDERPRODUCT ORDERPRODUCT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
