//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhareHouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.EXPIRATIONDATE = new HashSet<EXPIRATIONDATE>();
            this.ORDERDETAILS = new HashSet<ORDERDETAILS>();
            this.TICKETDETAILS = new HashSet<TICKETDETAILS>();
        }

        [Required(ErrorMessage = "Ingrese el ID del Producto")]
        public short IDBARCODE { get; set; }
        [Required(ErrorMessage = "Ingrese el codigo de barra")]
        [Range(1000000000000, 9999999999999, ErrorMessage = "Ingrese correctamente el codigo de barra, 13 digitos.")]
        public long BARCODE { get; set; }
        [Required(ErrorMessage = "Ingrese el precio de compra")]
        [Range(1, 9999999999, ErrorMessage = "Ingrese correctamente precio de compra.")]
        public int PURCHASEPRICE { get; set; }
        [Required(ErrorMessage = "Ingrese el precio de venta")]
        [Range(1, 9999999999, ErrorMessage = "Ingrese correctamente precio de venta.")]
        public int SALEPRICE { get; set; }
        [Required(ErrorMessage = "Ingrese el stock")]
        [Range(1, 99999, ErrorMessage = "Ingrese correctamente el stock.")]
        public short STOCK { get; set; }
        [Required(ErrorMessage = "Ingrese el stock critico")]
        [Range(1, 999, ErrorMessage = "Ingrese correctamente el stock critico")]
        public byte CRITICALSTOCK { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre del producto.")]
        [MaxLength(length: 30, ErrorMessage = "Maximo 30 caracteres")]
        [MinLength(length: 1)]
        public string PRODUCTNAME { get; set; }
        [Required(ErrorMessage = "Ingrese la familia del producto.")]
        [MaxLength(length: 30, ErrorMessage = "Maximo 30 caracteres")]
        [MinLength(length: 1)]
        public string PRODUCTFAMILY { get; set; }
        [Required(ErrorMessage = "Ingrese el tipo del producto.")]
        [MaxLength(length: 30, ErrorMessage = "Maximo 30 caracteres")]
        [MinLength(length: 1)]
        public string PRODUCTTYPE { get; set; }
        [Required(ErrorMessage = "Ingrese la descripcion del producto.")]
        [MaxLength(length: 30, ErrorMessage = "Maximo 100 caracteres")]
        [MinLength(length: 1)]
        public string PRODUCTDESCRIPTION { get; set; }
        public string STATE { get; set; }

        public short IDPROVIDER { get; set; }//Validar
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPIRATIONDATE> EXPIRATIONDATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAILS> ORDERDETAILS { get; set; }
        public virtual PROVIDER PROVIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETDETAILS> TICKETDETAILS { get; set; }
    }
}






















