//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhareHouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET()
        {
            this.TICKETDETAILS = new HashSet<TICKETDETAILS>();
        }
    
        public long IDTICKET { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}"),]
        public System.DateTime TICKETDATE { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm:ss}"),]
        public System.DateTime TICKETHOUR { get; set; }
        public string STATE { get; set; }
        public Nullable<long> TOTALTOTAL { get; set; }
        public Nullable<long> IDTRUSTED { get; set; }
        public Nullable<short> IDCLIENT { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual TRUSTED TRUSTED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETDETAILS> TICKETDETAILS { get; set; }
    }
}
