//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhareHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WhareHouseWebcn : DbContext
    {
        public WhareHouseWebcn()
            : base("name=WhareHouseWebcn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<EXPIRATIONDATE> EXPIRATIONDATE { get; set; }
        public virtual DbSet<ORDERDETAILS> ORDERDETAILS { get; set; }
        public virtual DbSet<ORDERPRODUCT> ORDERPRODUCT { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PROVIDER> PROVIDER { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<TICKETDETAILS> TICKETDETAILS { get; set; }
        public virtual DbSet<TRUSTED> TRUSTED { get; set; }
    }
}
