//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhareHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WhareHouseWebcn : DbContext
    {
        public WhareHouseWebcn()
            : base("name=WhareHouseWebcn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<EXPIRATIONDATE> EXPIRATIONDATE { get; set; }
        public virtual DbSet<ORDERDETAILS> ORDERDETAILS { get; set; }
        public virtual DbSet<ORDERPRODUCT> ORDERPRODUCT { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PROVIDER> PROVIDER { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<TICKETDETAILS> TICKETDETAILS { get; set; }
        public virtual DbSet<TRUSTED> TRUSTED { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
    
        public virtual int CREATESEQUENCECLIENT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATESEQUENCECLIENT");
        }
    
        public virtual int CREATESEQUENCEEXPIRATIONDATE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATESEQUENCEEXPIRATIONDATE");
        }
    
        public virtual int CREATESEQUENCEORDERPRODUCT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATESEQUENCEORDERPRODUCT");
        }
    
        public virtual int CREATESEQUENCEPRODUCT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATESEQUENCEPRODUCT");
        }
    
        public virtual int CREATESEQUENCEPROVIDER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATESEQUENCEPROVIDER");
        }
    
        public virtual int CREATESEQUENCETICKET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATESEQUENCETICKET");
        }
    
        public virtual int CREATESEQUENCETRUSTED()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATESEQUENCETRUSTED");
        }
    
        public virtual int SELECTSEQUENCECLIENT(ObjectParameter iDCLIENT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTSEQUENCECLIENT", iDCLIENT);
        }
    
        public virtual int SELECTSEQUENCEEXPIRATIONDATE(ObjectParameter iDEXPIRATIONDATE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTSEQUENCEEXPIRATIONDATE", iDEXPIRATIONDATE);
        }
    
        public virtual int SELECTSEQUENCEORDERPRODUCT(ObjectParameter iDORDERPRODUCT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTSEQUENCEORDERPRODUCT", iDORDERPRODUCT);
        }
    
        public virtual int SELECTSEQUENCEPRODUCT(ObjectParameter iDPRODUCT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTSEQUENCEPRODUCT", iDPRODUCT);
        }
    
        public virtual int SELECTSEQUENCEPROVIDER(ObjectParameter iDPROVIDER)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTSEQUENCEPROVIDER", iDPROVIDER);
        }
    
        public virtual int SELECTSEQUENCETICKET(ObjectParameter iDTICKET)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTSEQUENCETICKET", iDTICKET);
        }
    
        public virtual int SELECTSEQUENCETRUSTED(ObjectParameter iDTRUSTED)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTSEQUENCETRUSTED", iDTRUSTED);
        }
    }
}
